### ISSUE TITLE
Random InteropServices.COMException (0x80004005) while downloading file from MediaDevice

### ISSUE THREAD

**Issue by pallavi-garg** [Bassman2/MediaDevices#29]
Hi Ralf,

We have successfully integrated this library in our application and it is working pretty well.

While testing this with various devices, sometimes we see COMException while getting downloading file from the device though the file path is valid.

`System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at MediaDevices.Internal.IPortableDeviceResources.GetStream(String pszObjectID, PropertyKey& key, UInt32 dwMode, UInt32& pdwOptimalBufferSize, IStream& ppStream)
   at MediaDevices.Internal.Item.OpenRead()
   at MediaDevices.MediaDevice.DownloadFile(String path, Stream stream)
   at MTPDevice.<ImportData>d__a.MoveNext()`

We are wondering if you have seen this issue at some point or if there is some workaround or fix.
Any help is welcomed!

Thanks & Regards
Pallavi Garg

**Comment by Bassman2** [comment]
What framework do you use?

**Comment by PallaviGarg7** [comment]
We have windows application on .NET Framework 4.5 with x86 as target platform.

MedialDevices.dll version is 1.8.0.0. This is the signed version that we got from you in [issue 20](https://github.com/Bassman2/MediaDevices/issues/20).

Application is running on Windows 10 machine.

**Comment by PallaviGarg7** [comment]
Hi Ralf,

Did you get some time to look into this issue?

Regards
Pallavi

**Comment by Bassman2** [comment]
Hi Palavi, 

I changed the StreamWrapper class to fix the core download problem. Please check if this also fix your problem.

Regards
  Ralf

**Comment by chakflying** [comment]
Sorry as I am new to C# and nuget. How do I use the updated .dll locally? I tried just replacing the old .dll in `{my project}\packages\MediaDevices.1.8.0\lib\net45`, but build fails as it complains it cannot find the library.

**Comment by pallavi-garg** [comment]
Hi Ralf,

We are still facing this issue. Please let us know if you need some more details from us. 

Thanks
Pallavi Garg

**Comment by adamrkerr** [comment]
I found this because I'd been having this issue when transferring files from one (and only one) of my devices for a long time. For anyone else who finds this, updating to the latest version of MediaDevices, and upgrading my project to .Net Framework 4.7.2 seems to have finally fixed it.

For what it's worth, the device in question also displayed errors when attempting to copy the same files using Windows Explorer, and it displayed this behavior when connected to two different PCs. Whatever problem there was, it was something deep in the OS of the device.
