### ISSUE TITLE
Is it possible to download Files / Thumbnails async?

### ISSUE THREAD

**Issue by iDanielD** [Bassman2/MediaDevices#41]
Hey Bassman,

I just want to know if it is possible to download the files from the mobile phone async? 
Sorry I'm still new to github and also wanted to know if theres an another way to ask questions, since this one isn't really an Issue.

Thanks in advance
Daniel

**Comment by Bassman2** [comment]
Hi Daniel,

creating an issue for a question is OK.

MediaDevices is a .Net wrapper for the Windows MTP COM interface. The methods Read and Write from the IStream COM interface are used for uploading and downloading. This interface does not offer asynchronous access methods as in .NET. You could implement this with your own task so that it is asynchronous to the outside. However, this can also be done in the app.

Regards
   Ralf

**Comment by iDanielD** [comment]
Hey Ralf,

Thanks for the quick answer, could you give me an example, since I just can't get it to work.

**Comment by LittleLightCz** [comment]
Just in case somebody will stumble upon this, just as I did, this is one of the ways how to do it:
```c#
private static async Task MTPCopyAsync(MediaDevice device, MediaFileInfo srcFile, string trgFile, CancellationToken token)
{
    using var fileStream = File.Open(trgFile, FileMode.Create);
    using var srcStream = srcFile.OpenRead();
    await srcStream.CopyToAsync(fileStream, token);
}
```

And BTW thank you Ralf for this library, it's awesome!
