### ISSUE TITLE
Unable to get the file name containing special characters correctly

### ISSUE THREAD

**Issue by Acgnu** [Bassman2/MediaDevices#67]
**Describe the bug**
MediaDevice.GetFiles() Unable to get full file name on some special name

**To Reproduce**
file name exists in media device :    princess_connect!_re:dive skirt_lift tail.jpg
call method MediaDevice.GetFiles(), get file name :    dive skirt_lift tail.jpg

Calling MediaDevice.GetFileInfo() with an incomplete file name will cause an exception that the file does not exist.

**Expected behavior**
This file name is legal in Android. hope to get the complete file name

**Device**
Sanmsung Galaxy Note 10, SM-N9700

**Version:**
1.9.1

**Comment by Bassman2** [comment]
It was hard to reproduce since most devices for MTP don't use filesystems using Unix filenames.
The problem here is probably the System.IO.Path class that I use internally. This class does not support this feature in the .NET Framework (4.0, 4.5). The problem does not occur in .NET Core or .NET 5.0 and .NET 6.0.
Is this a solution for you to use a newer .Net?

**Comment by Acgnu** [comment]
My .NET version is 4.7.2.
I solved this problem with MediaDevice.EnumerateFiles(), it will return full name correctly.
tks.
