### ISSUE TITLE
Device cannot connect again

### ISSUE THREAD

**Issue by YogeshSanchania** [Bassman2/MediaDevices#76]
**Describe the bug**
Device cannot EnumerateFiles when reconnected. It gives exception "System.Runtime.InteropServices.COMException (0x802A0002): Shutdown was already called on this object or the object that owns it. (Exception from HRESULT: 0x802A0002)"

**To Reproduce**
1. Connect device "device.connect();"
2. EnumerateFiles
3. Device removed from PC
4. Device reconnected to PC
5. Repeat through step 1. and you will get exception on point 2.

**Expected behavior**
It should connect and enumerate files or any other operation.

**Device**
Any MTP device

**Version:**
1.9.1

**Additional context**

**Comment by voodoo84** [comment]
After reconnecting, are you reusing the old "device" reference, or you get a new one from the fresh MediaDevice.GetDevices() list?

**Comment by YogeshSanchania** [comment]
I use fresh MediaDevice.GetDevices(). old "device" references are set to null when device removed using "DeviceRemoved" event.

**Comment by voodoo84** [comment]
I don't have such problem, but I also refresh the list of drives on the device once I reconnect:

```
device.Connect();
string fileRoot = device.GetDrives().First().RootDirectory.FullName;
IEnumerable<string> dirs = device.EnumerateDirectories(fileRoot);
if (dirs.Contains(fileRoot + "\\Download")) fileRoot += "\\Download";
IEnumerable<string> files = device.EnumerateFiles(fileRoot, "*.mp4");
foreach (string file in files)
{
    ....
}
device.Disconnect();
```

**Comment by YogeshSanchania** [comment]
Can you please confirm you did not restarted the application?

**Comment by Bassman2** [comment]
I think the best way is to add https://github.com/Bassman2/UsbMonitor to your project to detect if a USB device was pluged in or out. Whith this information you can refresh your device list.

**Comment by YogeshSanchania** [comment]
I can detect USB pluged out with the help of "DeviceRemoved" event and when I connect device again I have a button where I perform fresh scan as below:

var device = MediaDevices().GetDevices().First(); //as of now only one so  I can work with first
device.connect();

var dirInfo = device.GetDirectoryInfo(device.GetRootDirectory().FullName);
var mp4Files = dirInfo.EnumerateFiles("*.mp4",SearchOption.AllDirectories);  // Getting Exception here

**Comment by FelixJongleur42** [comment]
Also having the Problem that the device does not reappear (iPhone) - not even in the File Explorer.
I can hear the USB sound for connection a USB device, but it does not show up.

**Comment by Bassman2** [comment]
Retry with version 1.10 and disabled cache. The slowly cache is the reason for a lot of problems.

**Comment by MartinKuschnik** [comment]
I can confirm this issue still exists in the current version. However, I believe the cache changes in recent commits don't address the root cause of this problem.


The issue lies in how `GetDevices()` manages the static `devices` field when no devices are connected:

```c#
public static IEnumerable<MediaDevice> GetDevices()
{
    deviceManager.RefreshDeviceList();
    uint count = 0;
    deviceManager.GetDevices(null, ref count);

    if (count == 0)
    {
        return new List<MediaDevice>(); // ❌ Returns empty list, but `devices` field remains unchanged!
    }

    // ... rest of the code
    if (devices == null)
    {
        devices = deviceIds.Select(d => new MediaDevice(d)).ToList();
    }
    else
    {
        UpdateDeviceList(devices, deviceIds);
    }
    return devices;
}

private static void UpdateDeviceList(List<MediaDevice> deviceList, string[] deviceIdList)
{
    var idList = deviceIdList.ToList();

    // remove
    var remove = deviceList.Where(d => !idList.Contains(d.DeviceId)).Select(d => d.DeviceId).ToList();
    deviceList.RemoveAll(d => remove.Contains(d.DeviceId));

    // add
    var add = idList.Where(id => !deviceList.Select(d => d.DeviceId).Contains(id)).ToList();
    deviceList.AddRange(add.Select(id => new MediaDevice(id)));
}

```

## What happens when a device is unplugged and reconnected

### Step 1: Device connected
- Static `devices` field contains: `[MediaDevice_1 with DeviceId="ABC"]`

### Step 2: Device disconnected
- `count == 0`
- Method returns empty list
- **BUT:** Static `devices` field still contains: `[MediaDevice_1]` ❌

### Step 3: Device reconnected
- `count > 0`
- `UpdateDeviceList()` is called
- **Problem:** `UpdateDeviceList()` sees the old `MediaDevice_1` with matching `DeviceId="ABC"` in both lists, so it **doesn't remove or replace it**

### Step 4: Result
- Application uses the stale `MediaDevice_1` object with an invalid/closed `IPortableDevice`
- **Exception thrown:** `COMException: "Shutdown was already called on this object"`


## Summary

The static device list needs proper lifecycle management to handle device disconnection/reconnection scenarios correctly. The core issues are:

1. When `count == 0`, the static `devices` field is never cleared
2. Stale `MediaDevice` objects are reused when devices reconnect with the same `DeviceId`
3. Removed devices are not disposed, causing resource leaks

This explains why reconnecting a device results in the "Shutdown was already called" exception - the cached `MediaDevice` object still references a closed/invalid `IPortableDevice` COM object.
